- .travis.yml
Looking at a recent Travis CI job:
```bash
npm WARN engine postcss-load-config@1.0.0: wanted: {"node":">=0.12","npm":">=3"} (current: {"node":"4.6.2","npm":"2.15.11"})
npm WARN engine postcss-load-plugins@2.0.0: wanted: {"node":">=0.12","npm":">=3"} (current: {"node":"4.6.2","npm":"2.15.11"})
npm WARN engine postcss-load-options@1.0.2: wanted: {"node":">=0.12","npm":">=3"} (current: {"node":"4.6.2","npm":"2.15.11"})
```
Adding `npm install -g npm` will install NPM 3.x, soon 4.x but will/should satisfy the above requirements.
See also https://github.com/postcss/postcss-loader/pull/140
> Use the latest NPM

- .travis.yml
> chore: Use Node.js 7.5.0 for Travis CI per package.json requirements

- package.json
Also, this PR replaces deprecated `eslint-plugin-node` rule.
- `node/no-unsupported-features` -> `node/no-unsupported-features/es-syntax`
- https://github.com/mysticatea/eslint-plugin-node/blob/v7.0.1/docs/rules/no-unsupported-features.md
- https://github.com/mysticatea/eslint-plugin-node/blob/v7.0.1/docs/rules/no-unsupported-features/es-syntax.md
Because `eslint-config-stylelint@8.2.0` upgraded `eslint-plugin-node` from `^5.2.1` to `^7.0.0`.
For details, please see <https://github.com/stylelint/eslint-config-stylelint/compare/8.1.0...8.2.0>.
Fixes #110
> Update eslint-config-stylelint to the latest version

- package.json
1. Use the tool [`babel-upgrade`](https://github.com/babel/babel-upgrade).
```sh
npx babel-upgrade --write
```
2. Install `@babel/register` package to avoid test error.
3. Remove `@babel/plugin-*` packages added by `babel-upgrade`.
4. Remove unused `babel-preset-react-hmre` package.
5. Remove unused `babel-plugin-webpack-loaders` package.
6. Add [`browserslist`](https://github.com/browserslist/browserslist) entry to `package.json`, which is used by [`@babel/preset-env`](https://babeljs.io/docs/en/babel-preset-env).
7. Update [`babel-eslint`](https://github.com/babel/babel-eslint) to latest version.
For details, please see [the migration guide](https://babeljs.io/docs/en/v7-migration).
Close #120
> Update dependencies to Babel 7

- package.json
- src/common/root/index.js
There is no much reason for this change. I just wanted to play with [hooks](https://reactjs.org/docs/hooks-intro.html) :)
I like how code gets cleaner with them. Check changes with the [split diff view](https://github.com/stylelint/stylelint-demo/pull/141/files?utf8=%E2%9C%93&diff=split).
> Refactor from classes to hooks

- package.json
- src/common/root/index.js
None.
I accidentally introduced a regression in #141. Demo calls `/lint` endpoint every 250ms all the time after loading.
> Fix /lint spam regression after #141

- package.json
- src/common/linter/index.css
- src/common/linter/index.js
- webpack.config.prod.js
We're using Ace as a code editor for the demo. It's a huuuge. Also, syntax highlighting almost non-existent.
I've replaced Ace with [react-simple-code-editor](https://github.com/satya164/react-simple-code-editor) and [Prism](https://prismjs.com/) for syntax hightlighting. [React Styleguidist](https://github.com/styleguidist/react-styleguidist) is using this combination and it's a popular project.
Two big improvements with new libraries:
1. Bundle size reduced **five** times! From 835KB to 163KB.
2. Syntax highlighting is so much better. I used the default Prism theme (with some tweaking for better JSON highlighting).
> Replace Ace with react-simple-code-editor

- .dependabot/config.yaml
- package-lock.json
- package.json
Pin [back](https://github.com/stylelint/stylelint-demo/pull/169) `react-simple-code-editor` to show line numbers. It was accidentally [updated](https://github.com/stylelint/stylelint-demo/pull/186) recently.
> Pin react-simple-code-editor to show line numbers

- .gitignore
- src/common/linter/index.css
Default size for a tab character is 8 spaces wide, which is too big. 4 spaces wide looks like a nice compromise between too big and too small like 2 spaces.
Before:
After:
> Use more sane tab-size for editors

- .github/workflows/nodejs.yml
- package.json
- Remove matrix. This project is *not* a library, so I think the matrix is needless.
- Unify `lint` and `test` jobs to one job for simplicity.
- Remove needless `CI: true` because it is set by default.
See <https://docs.github.com/en/actions/reference/environment-variables>.
- Bump actions/setup-node from v1 to v2.
See <https://github.com/actions/setup-node>.
Also,
- Update Node.js from v10 to v12. See <https://github.com/stylelint/stylelint-demo/pull/245#discussion_r589272158>.
None.
No, it's self-explanatory.
> Simplify CI configuration for Actions and update Node.js from v10 to v12

- src/common/linter/index.css
- src/common/warning-list/index.css
https://github.com/stylelint/stylelint.io/pull/174
It's a quick compatibility fix. Setting the background colour on the linter root stops the dark mode of docusaurus 2 bleeding through.
Can be merged as works with both docusaurus 1 and 2.
> Fix compat with docusaurus 2

- package-lock.json
- package.json
- src/common/editor/index.js
- src/common/lint-warning/index.css
- src/common/lint-warning/index.js
- src/common/linter/index.js
- src/common/warning-list/index.js
- src/server/__tests__/lint-test.js
- src/server/lint.js
None.
- Show a warning indicator in the editor UI; internally using Monaco Editor's model markers
See <https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-model-markers-example>
- Use metadata for a rule doc link
- Fix an invalid link for syntax error
- Update the `monaco-editor` package and add it to `dependencies` explicitly so that we can easily see it as outdated
> Improve Editor UI and fix bugs

- src/demo.css
None.
Moves installed deps alongside the package.json content to align and be more consistent with the `code` tab.
> Fix alignment of installed deps

- package-lock.json
- package.json
- postcss.config.mjs
- src/main.ts
- src/polyfills.ts
Closes #355
This change installs the `css-has-pseudo` PostCSS plugin, including a JS polyfill.
See https://github.com/csstools/postcss-plugins/tree/main/plugins/css-has-pseudo
[`:has()` on caniuse.com](https://caniuse.com/css-has)
> Add `:has()` polyfill for Firefox

- src/demo.css
None.
I think showing a message is more helpful than no output when there are no lint problems.
> Show message on no problems

- package-lock.json
- package.json
None.
`fs.rmSync()` is available on Node.js 18 instead.
See https://nodejs.org/api/fs.html#fsrmsyncpath-options
> Uninstall `rimraf` dependency

- .github/dependabot.yml
- package-lock.json
- package.json
Ref https://github.com/stylelint/stylelint.io/pull/341
This change makes Dependabot Pull Requests more efficient by grouping relevant dependencies' updates.
Also, this moves `monaco-editor` from `devDependencies` to `dependencies` since it's a runtime dependency.
See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
> Use Dependabot group updates

- package-lock.json
- package.json
- src/components/console.ts
- src/demo.css
- src/demo.html
- src/demo.ts
This PR changes to use xterm for the console display area.
The ANSI code was changed due to changes in Turborepo, so it was not displaying properly.
To solve this, change to using xterm to display the console.
before
after
No, it's self-explanatory.
> Use xterm for console display area

- package-lock.json
- package.json
- postcss.config.mjs
- src/main.ts
- src/polyfills.ts
Closes #362
My Firefox screenshot:
> Refactor to remove `:has()` polyfill

- package.json
None.
This PR makes this project ESM by adding `"type": "module"` to `package.json`.
By doing this, the following Vite warning disappears on `npm run build`:
```
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
```
> Refactor to enable ESM mode

- src/demo.css
The tab (Code, Config, Dependencies) is unnecessarily high, including extra margin, only on Firefox.
It's not a problem on Chrome or Safari.
None.
| [Before](https://chimerical-trifle-8d3c21.netlify.app/) | [After](https://deploy-preview-392--chimerical-trifle-8d3c21.netlify.app/) |
|--------|--------|
| <img width="302" alt="image" src="https://github.com/stylelint/stylelint-demo/assets/473530/40e8c8f7-e0ad-4a47-bbaa-aaa6a535ec43"> | <img width="281" alt="image" src="https://github.com/stylelint/stylelint-demo/assets/473530/83937732-0f06-4765-8842-c5825a1aa8cf"> |
> Fix tab height on Firefox

- .github/workflows/nodejs.yml
None.
We have the `.nvmrc` file and achieve DRY:
https://github.com/stylelint/stylelint-demo/blob/fff301fe883a8c7893f8cb074042c02fdd79ef8b/.nvmrc#L1
> Refactor CI config to use `node-version-file`

- package.json
- src/components/code-editor.ts
- src/components/config-editor.ts
- src/components/deps-editor.ts
- src/components/warnings.ts
- src/demo.css
- src/demo.html
- src/demo.ts
- src/monaco-editor/monaco-setup.ts
- src/style.css
None. I've been catching up on issues and PRs across the Stylelint org (amazing work btw!), and I wanted to dip my authoring toe back in with some CSS coding. 
This PR changes the output order to match the string formatter for consistency between the CLI and the online demo (location, severity, description, and name), as it's likely users of the online demo are reproducing an issue they first saw on the CLI.
Old:
New:
CLI (for reference):
To help make the fix, I also refactored [the CSS](https://github.com/stylelint/stylelint-demo/compare/fix-order-of-warnings-output?expand=1#diff-b4fde7f60d3bcf85b4177cf31a84117f0a1dec4b2da06e177c9e2b131d5dee38) and HTML code to use the type of …
> Fix inconsistent order of problems output between online demo and CLI

- src/linter-service/index.ts
None.
```
The glob option "as" has been deprecated in favour of "query". Please update `as: 'raw'` to `query: '?raw', import: 'default'`.
```
Ref https://vitejs.dev/guide/features#custom-queries
---
-- https://github.com/stylelint/stylelint-demo/actions/runs/10199201496/job/28215751741#step:9:15
> Fix Vite build deprecation warning

- src/demo.css
Follow-up to #413
I came across this issue on the dark mode supported by the demo site (https://stylelint.io/demo).
To reproduce it locally, edit `src/demo.css` like this:
```diff
/* Sectioning root */
body {
+		background-color: black;
color: var(--sd-black);
```
> Fix background color on dark mode

- src/components/config-editor.ts
- src/monaco-editor/monaco-loader.ts
- src/monaco-editor/monaco-setup.ts
- src/schema/stylelintrc.json
None.
The 3rd-party JSON schema provides auto-completion, validation, etc.
https://json.schemastore.org/stylelintrc
See also the [Monaco Editor Playground](https://microsoft.github.io/monaco-editor/playground.html?source=v0.51.0#example-extending-language-services-configure-json-defaults).
---
FYI, @Mouvedia has recently improved the schema with <https://github.com/SchemaStore/schemastore/pull/4057>. I appreciate that work. 👏🏼
> Add JSON Schema support for `.stylelintrc.json`

- .github/dependabot.yml
None
Reverts https://github.com/stylelint/stylelint-demo/pull/403 now that ESLint 9.x is used
> Revert 403 - include ESLint in dependabot development group

- src/schema/stylelintrc.json
Closes #445
examples of npm accounts of length 1
https://www.npmjs.com/~1
https://www.npmjs.com/~a
> Support namespaces not starting with `@` or of length 1

- package-lock.json
- package.json
None.
This change is generated by the following command:
```shell
npm rm @types/chokidar @types/eslint__js @types/lz-string @types/node
```
> Refactor to remove useless `@types/*` packages
