stylelint/stylelint-demo

- package.json
Closes #21
https://greenkeeper.io/
> chore(package): update react-ace to version 4.1.6

- .travis.yml
The last couple of merged PRs have failed on Travis. This was caused by an out of date Heroku API key, preventing Travis from deploying. Updating the Heroku API key should fix this.
> Fix failing deployments

- package.json
- src/common/linter/index.js
- src/common/warning-list/index.js
- src/common/warning/index.js
> Fix linter warnings in eslint-plugin-react v7

- package.json
- src/server/development-middleware.js
Adjusts the config to remove new warnings.
Replaces #73
> Update to eslint-config-stylelint version 8

- index.js
- package.json
- src/client/index.js
- src/common/linter/index.js
- src/common/root/index.js
- src/common/warning-list/index.js
- src/common/warning/index.js
- src/server/__tests__/lint-test.js
- src/server/development-middleware.js
- src/server/error-handler.js
- src/server/index.js
- src/server/lint.js
- webpack.config.dev.js
- webpack.config.prod.js
Same setup as we use for the stylelint repository. Prettier uses default settings. [lint-staged](https://github.com/okonet/lint-staged) ensures new code is formatted.
> Add Prettier and setup precommit hook for it

- package.json
> Update react/react-dom to version 16.5.1

- package.json
> chore(package): update webpack to version 4.19.1

- package.json
> chore(package): update webpack-hot-middleware to version 2.24.0

- .postcssrc
- package.json
Closes #123 
Closes https://github.com/stylelint/stylelint-demo/pull/101
Moved the config to `package.json` to co-exist with the browerslist and babel ones.
> Use postcss-preset-env

- package.json
- src/common/warning-list/index.js
- src/server/__tests__/lint-test.js
- src/server/index.js
- src/server/lint.js
Supersedes https://github.com/stylelint/stylelint-demo/pull/125
> Bump all dependencies

- src/common/linter/index.css
- src/common/linter/index.js
- src/common/root/index.js
- src/common/syntax-select/index.css
- src/common/syntax-select/index.js
- src/server/__tests__/lint-test.js
- src/server/lint.js
> Add syntax select

- src/common/syntax-select/index.css
To address hidden text on Windows.
Closes #139
> Fix Syntax Select background

- package.json
- src/server/__tests__/lint-test.js
> Switch test framework over to Jest. Closes #80

- src/common/syntax-select/index.js
Reflecting change in [stylelint@9.10.0](https://stylelint.io/CHANGELOG/#9100).
> Add CSS-in-JS syntax

- package-lock.json
- package.json
- src/common/root/index.js
- src/common/utils.js
closes https://github.com/stylelint/stylelint-demo/issues/16
I think nothing
> feat: added ability to share REPL using link

- src/server/lint.js
Fixes #155.
Currently blocked, because we need to release stylelint first. (11.0.1+).
> Support "css" syntax option

- src/common/lint-warning/index.css
- src/common/lint-warning/index.js
- src/common/linter/index.js
- src/common/root/index.js
- src/common/severity-label/index.css
- src/common/severity-label/index.js
- src/common/warning-list/index.css
- src/common/warning-list/index.js
- src/server/__tests__/lint-test.js
- src/server/lint.js
> Add invalid option warnings, update tests

- src/common/lint-warning/index.js
- src/common/linter/index.js
- src/common/root/index.js
- src/common/severity-label/index.js
- src/common/warning-list/index.js
- src/server/__tests__/lint-test.js
- src/server/lint.js
- src/server/utils.js
Parse errors added. It should fix #27 .
No, it's self explanatory.
> Add parseErrors warnings, add tests (#27)

- package-lock.json
- package.json
Reverts stylelint/stylelint-demo#205
This quicker... ;)
> Revert "Bump jest from 25.1.0 to 25.2.7"

- package-lock.json
- package.json
- src/common/syntax-select/index.js
None.
Reintroducing HTML syntax option now that the package is maintained and compatible.
> Readd HTML syntax

- .gitignore
- src/common/lint-warning/index.js
- src/common/linter/index.js
- src/server/__tests__/lint-test.js
- src/server/lint.js
None.
I think it's easier to view if the warnings are sorted by location (line and column). What do you think?
See the [demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYLIBsBO8UGIAzQgbhQF8AdAOxABoQBnAT2oBckAPBcRx+8BGqEAlgHMewGihSUQ2AK6YYjOXinUZMuUjYBaRcr3UIehdQDWJgO7U1KNoph1pWuQCNMEMBeOmYALYADmzM9o4Kzq7agl7Yfnoi1ABuSJgiUHoAFjCc4U4umm6CAQEw7AmBIWEIDgXRsuAKjGwQAXpB2BBBMNihCQEifElieqnxhOZgbCJC+ZGFWo2wYJhI2Lqz1Hqe3r4melAKQelgujB6YM2t7Z3dvTMq81FFMStrGzNCO14+CUcnERnNgXO49PoiJ61ADaDRkEReSxkGiRxXEJmwMHssNeqMakGojBgVxmyQuANO50YemsIjYWUOImIvXK+lSmEiqhAcK0AF0eVRcbzFsV3utNt9dn8DowshA+lkkNRMmCHsw9BAydhsBkoXgESKYoQhPpCEhBph1QcKUDzsZzXq6gsGnJjRUzRaraZBsNqKMxOVekC9B6RJa9BYYMxrPKoM9DY1JtRpltLm …
> Sort lint warnings by line and column

- README.md
None, as it's a documentation fix.
Latest build is live at https://stylelint.io/demo
> Document git deployment

- package.json
- src/client/index.ejs
- src/common/lint-warning/index.css
- src/common/linter/index.css
- src/common/severity-label/index.css
- src/common/syntax-select/index.css
- src/common/warning-list/index.css
None.
CSS Custom Properties are supported on all modern browsers.
https://caniuse.com/css-variables
> Refactor to use custom property for font family

- .github/workflows/nodejs.yml
- package.json
Ref: https://github.com/stylelint/.github/pull/12
- Move `npm run posttest` into `npm test`
- Add lint job to CI
> Make npm scripts consistent across our repos

- README.md
None.
No, it's self-explanatory.
> Add Netlify status badge to README

- src/components/warnings.ts
Closes #417
This PR uses the `invalidOptionWarnings` property. See:
https://github.com/stylelint/stylelint/blob/462cdab4c08231b310c4d428cafc6eff01051e2b/docs/developer-guide/formatters.md?plain=1#L40
> Add support for showing invalid rule options warnings

- src/schema/stylelintrc.json
Closes #438
https://github.com/sindresorhus/scoped-regex/blob/6b4b9ac4fe20cebd0c343a7b2f88c9ce09b6ca22/index.js#L1
> Add support for namespaced rules

- src/schema/stylelintrc.json
Closes #452
https://github.com/stylelint/stylelint/blob/main/types/stylelint/index.d.ts#L7
e.g. `["qux", { "rule": {}, "ruleName": "foo/bar" }]`
> Fix `plugins` type

- src/schema/stylelintrc.json
#448
This is the first part of #448.
> Add 5 rules and 1 option to `stylelintrc.json`

- .vscode/settings.json
- src/demo.ts
- src/linter-service/server/server.mjs
- src/monaco-editor/monaco-setup.ts
Closes #458
This PR adds support for quick fixes.
I think you can try the following code:
CODE: 
```css
a { color: rgb(0 0 0 / 0.5) }
```
The `computeEditInfo` option is not released, so please use the current main branch package released in `pkg.pr.new`:
Dependencies:
```json
{
"stylelint": "https://pkg.pr.new/stylelint@eec62e5",
"stylelint-config-standard": "latest"
}
```
> Add support for quick fixes

- src/schema/stylelintrc.json
followup of #457
#448
stylelint/stylelint#8668
stylelint/stylelint#8331
This PR reduces the number of lines of the schema by more than 400.
> Add `media-type-no-deprecated` and `syntax-string-no-invalid` to stylelintrc.json
